from functools import partial

from openid import xrds
from openid.yadis.discover import fetch_data, DiscoveryFailure


def getServiceEndpoints(url, types, constructor):
    """Perform the Yadis protocol on the input URL and return an
    iterable of resulting endpoint objects.

    @param flt: A filter object or something that is convertable to
        a filter object (using mkFilter) that will be used to generate
        endpoint objects. This defaults to generating BasicEndpoint
        objects.

    @param url: The URL on which to perform the Yadis protocol

    @return: The normalized identity URL and an iterable of endpoint
        objects generated by the filter function.

    @rtype: (str, [endpoint])

    @raises DiscoveryFailure: when Yadis fails to obtain an XRDS document.
    """
    try:
        et = xrds.parseXRDS(fetch_data(url))
        endpoints = parse_services(url, et, types, constructor)
    except xrds.XRDSError as err:
        raise DiscoveryFailure(str(err), None)
    return (url, endpoints)


def matches_types(element, types):
    return not types or \
           set(types).intersection(set(xrds.getTypeURIs(element)))


def filter_services(types, constructor, yadis_url, elements):
    elements = [e for e in elements if matches_types(e, types)]
    result = []
    for element in elements:
        uris = xrds.sortedURIs(element)
        endpoints = [constructor(uri, yadis_url, element) for uri in uris]
        result.extend(endpoints)
    return result


def parse_services(uri, et, types, constructor):
    if not hasattr(et, 'getroot'):
        et = xrds.parseXRDS(et)
    return filter_services(types, constructor, uri, xrds.iterServices(et))
